name: metrdotel
description: Restaurant booking app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.1.1
  get_it: ^5.0.3
  logger: ^0.9.4
  injectable: ^1.0.5
  flutter_bloc: ^6.1.1
  auto_route: ^0.6.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  auto_route_generator:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/sipping_coffee.png
    - images/eating_with_chopsticks.png
    - images/couple.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Black.ttf
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
        - asset: fonts/poppins/Poppins-Thin.ttf
          style: italic
    - family: Butler
      fonts:
        - asset: fonts/butler/Butler_Black.otf
        - asset: fonts/butler/Butler_ExtraBold.otf
        - asset: fonts/butler/Butler_Bold.otf
        - asset: fonts/butler/Butler_Medium.otf
        - asset: fonts/butler/Butler_Regular.otf
        - asset: fonts/butler/Butler_Light.otf
        - asset: fonts/butler/Butler_Ultra_Light.otf
